
package forms;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;


public class frmClientDetails extends javax.swing.JFrame {
ResultSet rs;
PreparedStatement pstmt;
Connection conn;
boolean add,edit;
int getMaxCID;

    public frmClientDetails() {
        initComponents();
        doConnect();
        disableTexts();
        fillClientTable();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(frmClientDetails.DISPOSE_ON_CLOSE);
       
    }
    private void fillClientTable(){
        try{
            pstmt = conn.prepareStatement("SELECT cd_cid,cd_name,cd_poc,cid_email,cd_contact "
                    + "from tblClientDetails order by cd_name");
            rs = pstmt.executeQuery();
            tblClient.setModel(DbUtils.resultSetToTableModel(rs));
            pstmt.close();
            tblClient.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblClient.getColumnModel().getColumn(1).setHeaderValue("NAME");
            tblClient.getColumnModel().getColumn(2).setHeaderValue("POC");
            tblClient.getColumnModel().getColumn(3).setHeaderValue("EMAIL");
            tblClient.getColumnModel().getColumn(4).setHeaderValue("CONTACT");
        }catch(SQLException e){
            e.getMessage();
        }
    }
    private void disableTexts(){
        txtClientAddress.setEnabled(false);
        txtClientEmail.setEnabled(false);
        txtClientName.setEnabled(false);
        txtClientPOC.setEnabled(false);
        txtContact.setEnabled(false);
        lblID.setEnabled(false);
    }
    private void enableTexts(){
        txtClientAddress.setEnabled(true);
        txtClientEmail.setEnabled(true);
        txtClientName.setEnabled(true);
        txtClientPOC.setEnabled(true);
        txtContact.setEnabled(true);
        lblID.setEnabled(true);
    }
    private void clearTexts(){
        txtClientAddress.setText("");
        txtClientEmail.setText("");
        txtClientName.setText("");
        txtClientPOC.setText("");
        txtContact.setText("");
        lblID.setText("");
    }
    private void doConnect(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
//        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbticketing","root","root");
//        conn = DriverManager.getConnection("jdbc:mysql://192.168.1.13/dbticketing","iSoft","iSoft123");
        conn = DriverManager.getConnection("jdbc:mysql://192.168.100.2/dbticketing","iSoft","iSoft123");
    }catch(SQLException | ClassNotFoundException e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClientAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        txtClientPOC = new javax.swing.JTextField();
        txtClientEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 770, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 50));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel5.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, 50));

        btnDelete.setText("DELETE");
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 50));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, 50));

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 20));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 270, 160));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel3.setText("CID:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel4.setText("CONTACT NUMBERS:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel5.setText("ADDRESS:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 180, 30));

        txtClientAddress.setColumns(20);
        txtClientAddress.setRows(5);
        jScrollPane1.setViewportView(txtClientAddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 250, 120));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel7.setText("NAME:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 30));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 30));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setText("POINT OF CONTACT:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        lblID.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 120, 30));

        txtContact.setNextFocusableComponent(txtClientAddress);
        jPanel4.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 270, 30));

        txtClientName.setFocusCycleRoot(true);
        txtClientName.setNextFocusableComponent(txtClientPOC);
        jPanel4.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 270, 30));

        txtClientPOC.setNextFocusableComponent(txtClientEmail);
        jPanel4.add(txtClientPOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 270, 30));

        txtClientEmail.setNextFocusableComponent(txtContact);
        jPanel4.add(txtClientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 270, 30));

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClient);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 440, 160));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 400));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 770, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add = true;
        edit = false;
        btnEdit.setEnabled(false);
        enableTexts();
        clearTexts();
        getNextCID();
        lblID.setText(String.valueOf(getMaxCID));
        txtClientName.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed
    private void getNextCID(){
        try{
            pstmt = conn.prepareStatement("select cd_cid from tblClientDetails order by cd_cid DESC LIMIT 1");
            rs = pstmt.executeQuery();
            if (rs.next()){
                getMaxCID = rs.getInt("cd_cid");
                getMaxCID++;
            }else{
                getMaxCID = 1;
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       if (txtClientName.getText().equals("")){
           JOptionPane.showMessageDialog(this, "PLEASE TYPE CLIENT NAME","CLIENT DETAILS", JOptionPane.WARNING_MESSAGE);
       }else{
        if (add==true && edit==false){
            String insertClientDetails = "INSERT INTO tblClientDetails (cd_cid,cd_name,cd_address,"
                    + "cd_poc,cid_email,cd_contact) values (?,?,?,?,?,?)";
            try{
                pstmt = conn.prepareStatement(insertClientDetails);
                pstmt.setString(1,lblID.getText());
                pstmt.setString(2,txtClientName.getText());
                pstmt.setString(3,txtClientAddress.getText());
                pstmt.setString(4,txtClientPOC.getText());
                pstmt.setString(5,txtClientEmail.getText());
                pstmt.setString(6,txtContact.getText());
                pstmt.execute();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "CLIENT DETAILS SAVED");
                clearTexts();
                disableTexts();
                btnEdit.setEnabled(true);
                fillClientTable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else if (add==false && edit== true){
            String editClientDetails = "UPDATE tblClientDetails set cd_name=?,cd_address=?,"
                    + "cd_poc=?,cid_email=?,cd_contact=? where cd_cid=?";
            try{
                pstmt = conn.prepareStatement(editClientDetails);
                pstmt.setString(1,txtClientName.getText());
                pstmt.setString(2,txtClientAddress.getText());
                pstmt.setString(3,txtClientPOC.getText());
                pstmt.setString(4,txtClientEmail.getText());
                pstmt.setString(5,txtContact.getText());
                pstmt.setString(6,lblID.getText());
                pstmt.execute();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "CLIENT DETAILS UPDATED");
                clearTexts();
                disableTexts();
                btnAdd.setEnabled(true);
                fillClientTable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit=true;
        add=false;
        enableTexts();
        btnAdd.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearTexts();
        disableTexts();
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        int row = tblClient.getSelectedRow();
        int ba = tblClient.convertRowIndexToModel(row);
            String tblClick = tblClient.getModel().getValueAt(ba, 0).toString();
            String fetchData = "Select * from tblClientDetails where cd_cid=?";
        try{
            pstmt = conn.prepareStatement(fetchData);
            pstmt.setString(1, tblClick);
            rs = pstmt.executeQuery();
            if (rs.next()){
                lblID.setText(String.valueOf(rs.getInt("cd_cid")));
                txtClientName.setText(rs.getString("cd_name"));
                txtClientAddress.setText(rs.getString("cd_address"));
                txtClientPOC.setText(rs.getString("cd_poc"));
                txtClientEmail.setText(rs.getString("cid_email"));
                txtContact.setText(rs.getString("cd_contact"));
            }
            pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        try{
            frmDashboard obj = new frmDashboard();
            obj.setVisible(true);
            this.dispose();
            rs.close();
            conn.close();
            pstmt.close();
        }catch(SQLException e){
            e.getMessage();
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextArea txtClientAddress;
    private javax.swing.JTextField txtClientEmail;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientPOC;
    private javax.swing.JTextField txtContact;
    // End of variables declaration//GEN-END:variables
}
