
package forms;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class frmClient extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
PreparedStatement pstmt;
DecimalFormat df = new DecimalFormat("#.000");
boolean add,edit;
int getMaxClientID,getSelectedID;
    public frmClient() {
        initComponents();
        doConnect();
        fillTable();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(frmClient.DISPOSE_ON_CLOSE);
    }
    private void getNextID(){
        try{
            pstmt = conn.prepareStatement("SELECT * from tblClientList order by cl_id DESC LIMIT 1");
            rs = pstmt.executeQuery();
            if (rs.next()){
                getMaxClientID = rs.getInt("cl_id");
                getMaxClientID++;
            }else{
                getMaxClientID =1;
            }
            pstmt.close();
        }catch(SQLException e){
            e.getMessage();
        }
    }
    private void fillTable(){
        try{
            pstmt = conn.prepareStatement("Select * from tblClientList order by cl_company");
            rs = pstmt.executeQuery();
            tblClient.setModel(DbUtils.resultSetToTableModel(rs));
            pstmt.close();
            tblClient.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblClient.getColumnModel().getColumn(1).setHeaderValue("COMPANY");
            tblClient.getColumnModel().getColumn(2).setHeaderValue("CONTACT PERSON");
            tblClient.getColumnModel().getColumn(3).setHeaderValue("ADDRESS");
            tblClient.getColumnModel().getColumn(4).setHeaderValue("PHONE/MOBILE");
            tblClient.getColumnModel().getColumn(5).setHeaderValue("EMAIL");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void doConnect(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
//        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbticketing","root","root");
//        conn = DriverManager.getConnection("jdbc:mysql://192.168.1.13/dbticketing","iSoft","iSoft123");
        conn = DriverManager.getConnection("jdbc:mysql://192.168.100.2/dbticketing","iSoft","iSoft123");
    }catch(SQLException | ClassNotFoundException e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClientAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtClientContact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClientEmail = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtClientCompany = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENT LIST");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 890, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        txtClientAddress.setColumns(20);
        txtClientAddress.setRows(5);
        jScrollPane1.setViewportView(txtClientAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 450, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone/Mobile:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 90, 30));
        jPanel1.add(txtClientContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 90, 30));
        jPanel1.add(txtClientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 220, 30));
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 450, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Company:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));
        jPanel1.add(txtClientCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 450, 30));

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClient);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 890, 420));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 90, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 90, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 90, -1));

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add = true;
        edit = false;
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        add = false;
        edit = true;
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        getNextID();
        String insertQuery = "INSERT INTO tblClientList(cl_id,cl_company,cl_contactperson,cl_address,cl_contact,cl_email)"
        + " values (?,?,?,?,?,?)";
        String editQuery = "UPDATE tblClientList set cl_contactperson=?,cl_address=?,cl_contact=?,cl_email=? where cl_id=? and cl_company=? and cl_contactperson=?";
        if (add==true  && edit==false){
            try{
                pstmt = conn.prepareStatement(insertQuery);
                pstmt.setInt(1,getMaxClientID);
                pstmt.setString(2, txtClientCompany.getText());
                pstmt.setString(3, txtClientName.getText());
                pstmt.setString(4, txtClientAddress.getText());
                pstmt.setString(5, txtClientContact.getText());
                pstmt.setString(6, txtClientEmail.getText());       
                pstmt.execute();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "CLIENT ADDED");
                fillTable();
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(true);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else if(edit==true && add==false){
            try{
                pstmt = conn.prepareStatement(editQuery);
                pstmt.setString(1, txtClientName.getText());
                pstmt.setString(2, txtClientAddress.getText());
                pstmt.setString(3, txtClientContact.getText());
                pstmt.setString(4, txtClientEmail.getText()); 
                pstmt.setInt(5,getSelectedID);
                pstmt.setString(6, txtClientCompany.getText());
                pstmt.setString(7, txtClientName.getText());
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "CLIENT DETAILS UPDATED");
                fillTable();
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(true);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        int row = tblClient.getSelectedRow();
        int ba = tblClient.convertRowIndexToModel(row);
        int tblClick = Integer.valueOf(tblClient.getModel().getValueAt(ba, 0).toString());
        String tblClickCompany = tblClient.getModel().getValueAt(ba, 1).toString();
        String fetchData = "select * from tblClientList where cl_id=? and cl_company=?";
        try{
            pstmt = conn.prepareStatement(fetchData);
            pstmt.setInt(1, tblClick);
            pstmt.setString(2,tblClickCompany);
            rs = pstmt.executeQuery();
            if (rs.next()){
                txtClientAddress.setText(rs.getString(4));
                txtClientCompany.setText(rs.getString(2));
                txtClientContact.setText(rs.getString(5));
                txtClientEmail.setText(rs.getString(6));
                txtClientName.setText(rs.getString(3));
                getSelectedID = rs.getInt(1);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tblClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextArea txtClientAddress;
    private javax.swing.JTextField txtClientCompany;
    private javax.swing.JTextField txtClientContact;
    private javax.swing.JTextField txtClientEmail;
    private javax.swing.JTextField txtClientName;
    // End of variables declaration//GEN-END:variables
}
