
package forms;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class frmServices extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
PreparedStatement pstmt;
DecimalFormat df = new DecimalFormat("#.000");
int getMaxID;
boolean add,edit;
    public frmServices() {
        initComponents();
        doConnect();
        fillTable();
        txtServiceName.setWrapStyleWord(true);
        txtServiceName.setLineWrap(true);
        setDefaultCloseOperation(frmClient.DISPOSE_ON_CLOSE);
    }
    private void disableTexts(){
        txtPrice.setEditable(false);
        txtServiceName.setEditable(false);
    }
    private void enableTexts(){
        txtPrice.setEditable(true);
        txtServiceName.setEditable(true);
    }
    private void doConnect(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
//        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbticketing","root","root");
//        conn = DriverManager.getConnection("jdbc:mysql://192.168.1.13/dbticketing","iSoft","iSoft123");
        conn = DriverManager.getConnection("jdbc:mysql://192.168.100.2/dbticketing","iSoft","iSoft123");
    }catch(SQLException | ClassNotFoundException e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }
    private void fillTable(){
        try{
            pstmt = conn.prepareStatement("SELECT * from tblServiceList order by sl_id");
            rs = pstmt.executeQuery();
            tblService.setModel(DbUtils.resultSetToTableModel(rs));
            tblService.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblService.getColumnModel().getColumn(1).setHeaderValue("SERVICE");
            tblService.getColumnModel().getColumn(2).setHeaderValue("PRICE");
        }catch(SQLException e){
            e.getMessage();
        }
    }
    private void getNextID(){
        try{
            pstmt = conn.prepareStatement("Select * from tblServiceList order by sl_id DESC LIMIT 1");
            rs = pstmt.executeQuery();
            if (rs.next()){
                getMaxID = rs.getInt(1);
                getMaxID++;
            }else{
                getMaxID = 1;
            }
            lblServiceID.setText(String.valueOf(getMaxID));
            pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblServiceID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServiceName = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERVICES LIST");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, 740, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 790, 30));

        jLabel3.setText("SERVICE ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        lblServiceID.setText("SERVICE ID");
        jPanel1.add(lblServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 30));

        jLabel2.setText("SERVICE DESCRIPTION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 30));

        txtServiceName.setColumns(20);
        txtServiceName.setRows(5);
        jScrollPane1.setViewportView(txtServiceName);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 160));

        jLabel4.setText("PRICE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 30));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, 30));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 90, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 90, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 90, -1));

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 90, -1));

        btnClose.setText("CLOSE");
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 90, -1));

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblService);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 90, 410, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        getNextID();
        add = true;
        edit = false;
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        txtPrice.setText("");
        txtServiceName.setText("");
        enableTexts();
        txtServiceName.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        add = false;
        edit = true;
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        enableTexts();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String insertProductQuery = "INSERT INTO tblServiceList(sl_id,sl_name,sl_price)"
        + " values (?,?,?)";
        String editProductQuery = "UPDATE tblServiceList set sl_name=?,sl_price=? where sl_id=?";
        if (add==true  && edit==false){
            try{
                pstmt = conn.prepareStatement(insertProductQuery);
                pstmt.setInt(1, getMaxID);
                pstmt.setString(2,txtServiceName.getText() );
                pstmt.setString(3, df.format(Double.valueOf(txtPrice.getText())));
                pstmt.execute();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "SERVICE SAVED");
                txtPrice.setText("");
                txtServiceName.setText("");
                lblServiceID.setText("");
                fillTable();
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(true);
                disableTexts();
            }catch(SQLException e){
                e.getMessage();
            }
        }else if(edit==true && add==false){
            try{
                pstmt = conn.prepareStatement(editProductQuery);
                pstmt.setString(1,txtServiceName.getText());
                pstmt.setString(2,df.format(Double.valueOf(txtPrice.getText())));
                pstmt.setInt(3, Integer.valueOf(lblServiceID.getText()));
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "SERVICE DETAILS UPDATED");
                txtPrice.setText("");
                txtServiceName.setText("");
                lblServiceID.setText("");
                fillTable();
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(true);
                disableTexts();
            }catch(SQLException e){
                e.getMessage();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtPrice.setText("");
        txtServiceName.setText("");
        lblServiceID.setText("");
        disableTexts();
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        int row = tblService.getSelectedRow();
        int ba = tblService.convertRowIndexToModel(row);
        String tblClick = tblService.getModel().getValueAt(ba, 0).toString();
        String fetchData = "SELECT * from tblServiceList where sl_id=?";
        try{
            pstmt = conn.prepareStatement(fetchData);
            pstmt.setString(1,tblClick);
            rs = pstmt.executeQuery();
            if (rs.next()){
                lblServiceID.setText(rs.getString("sl_id"));
                txtPrice.setText(rs.getString("sl_price"));
                txtServiceName.setText(rs.getString("sl_name"));
            }
            pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tblServiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblServiceID;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextArea txtServiceName;
    // End of variables declaration//GEN-END:variables
}
