
package forms;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class frmTimeKeeping extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
PreparedStatement pstmt;
int getMaxID;
SimpleDateFormat sdfTime = new SimpleDateFormat("hh:mm a");
SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
DecimalFormat df = new DecimalFormat ("#.00");
long endtime,startTime;
    public frmTimeKeeping() {
        initComponents();
        doConnect();
        setDefaultCloseOperation(frmTimeKeeping.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        lblTime.setText("");
    }
    public void doConnect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
//            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbticketing","root","root");
    //        conn = DriverManager.getConnection("jdbc:mysql://192.168.1.13/dbticketing","iSoft","iSoft123");
            conn = DriverManager.getConnection("jdbc:mysql://192.168.100.2/dbticketing","iSoft","iSoft123");
        }catch(SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin.setText("CLOCK IN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 50));

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogout.setText("CLOCK OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, 50));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("TIME LOG");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getNextID(){
        try{
            pstmt = conn.prepareStatement("Select tk_id from tblTimeKeeping order by tk_id DESC LIMIT 1");
            rs = pstmt.executeQuery();
            if (rs.next()){
               getMaxID = rs.getInt(1);
                getMaxID++;
            }else{
                getMaxID = 1;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        getNextID();
        startTime = System.currentTimeMillis();
        Date getCurrentTime = new Date(startTime);
        try{
            pstmt = conn.prepareStatement("select * from tblTimeKeeping where tk_name=? and tk_date=? and tk_login is not null");
            pstmt.setString(1, frmLogin.username);
            pstmt.setString(2,sdfDate.format(getCurrentTime));
            rs = pstmt.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(this, "YOU HAVE LOGGED IN FOR TODAY");
            }else{
                pstmt = conn.prepareStatement("INSERT INTO tblTimeKeeping (tk_id,tk_name,tk_login,tk_date) values (?,?,?,?)");
                pstmt.setInt(1,getMaxID);
                pstmt.setString(2, frmLogin.username);
                pstmt.setString(3, sdfTime.format(getCurrentTime));
                pstmt.setString(4,String.valueOf(sdfDate.format(getCurrentTime)));
                pstmt.execute();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "LOG IN SUCCESSFULLY");
                lblTime.setText(String.valueOf(sdfTime.format(getCurrentTime)));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        endtime = System.currentTimeMillis();
        Date getCurrentTime = new Date(endtime);
        double totalHours =0;
        //get the login hours for the day
        try{
            pstmt = conn.prepareStatement("SELECT tk_login from tblTimeKeeping where tk_date=?");
            pstmt.setString(1,sdfDate.format(getCurrentTime));
            rs = pstmt.executeQuery();
            if (rs.next()){
                //save the logout and calculate hours     
                String queryLogout = "UPDATE tblTimeKeeping set tk_logout=?,tk_hours=? where tk_date =? and tk_name=? and tk_logout is null";
                pstmt = conn.prepareStatement(queryLogout);
                pstmt.setString(1,String.valueOf(sdfTime.format(getCurrentTime)));
                //get Hours
                String getLogin = rs.getString("tk_login");
                Date timeIn = sdfTime.parse(getLogin);
                Date timeOut = sdfTime.parse(sdfTime.format(getCurrentTime));
                totalHours = Math.abs(timeIn.getTime() - timeOut.getTime()) / 1000 / 60;
                Double conHours = totalHours /60;
                pstmt.setString(2,df.format(conHours));
                pstmt.setString(3,sdfDate.format(getCurrentTime));
                pstmt.setString(4,frmLogin.username);
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "LOGOUT SUCCESSFULLY");
                lblTime.setText(String.valueOf(sdfTime.format(getCurrentTime)));
            }else{
                JOptionPane.showMessageDialog(this, "NO LOGIN FOR TODAY");
                return;
            }
            pstmt.close();
        }catch(SQLException | ParseException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
       
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTimeKeeping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
